/* Copyright 2019,2020 NXP
 *
 * This software is owned or controlled by NXP and may only be used
 * strictly in accordance with the applicable license terms.  By expressly
 * accepting such terms or by downloading, installing, activating and/or
 * otherwise using the software, you are agreeing that you have read, and
 * that you agree to comply with and are bound by, such license terms.  If
 * you do not agree to be bound by the applicable license terms, then you
 * may not retain, install, activate or otherwise use the software.
 *
 */

#ifndef MALS_AGENT_VERSION_INFO_H_INCLUDED
#define MALS_AGENT_VERSION_INFO_H_INCLUDED

/* clang-format off */
#define MALS_AGENT_PROD_NAME          "MALS_Agent"
#define MALS_AGENT_VER_STRING_NUM     "v00.04.00_20200219"
#define MALS_AGENT_PROD_NAME_VER_FULL "MALS_Agent_v00.04.00_20200219"
#define MALS_AGENT_VER_MAJOR          (0u)
#define MALS_AGENT_VER_MINOR          (4u)
#define MALS_AGENT_VER_DEV            (0u)

/* v00.04 = 4u */
#define MALS_AGENT_VER_MAJOR_MINOR ( 0 \
    | (MALS_AGENT_VER_MAJOR * 10000u)    \
    | (MALS_AGENT_VER_MINOR))

/* v00.04.00 = 40000ULL */
#define MALS_AGENT_VER_MAJOR_MINOR_DEV ( 0 \
    | (MALS_AGENT_VER_MAJOR * 10000*10000u)    \
    | (MALS_AGENT_VER_MINOR * 10000u)    \
    | (MALS_AGENT_VER_DEV))

/* clang-format on */

/* Version Information:
 * Generated by:
 *     scripts\version_info.py (v2019.01.17_00)
 *
 * Do not edit this file. Update:
 *     mal/version_info.txt instead.
 *
 * prod_name = "MALS_Agent"
 *
 * prod_desc = "MALS Agent"
 *
 * lang_c_prefix = prod_name.upper()
 *
 * lang_namespace = ""
 *
 * v_major  = "00"
 *
 * v_minor  = "04"
 *
 * v_dev    = "00"
 *
 * v_meta   = ""
 *
 * maturity = "B"
 *
 * #
 * # v00.04.00 : Use channel 0
 * #
 * # v00.03.00 : Use channel 1
 * #
 */

#endif /* MALS_AGENT_VERSION_INFO_H_INCLUDED */
