
#ifndef _BOARD_SELECTION_PC_H
#define _BOARD_SELECTION_PC_H

#define RESET_POWERUP_LEVEL 1
#define RESET_POWERDOWN_LEVEL 1
#define RESET_POWERUP_LEVEL  1
//#define PH_NXPNFCRDLIB_CONFIG_RC663_IRQ_TYPE 1

#endif /* _BOARD_SELECTION_PC_H */